Authorize only actual operation
graphql-dotnet/authorization pull request #171
Opened 2021-12-07 06:02 UTC by SlavaUtesinov

This is a possible fix of the issue #5.

2021-12-07 09:29 UTC, sungam3r commented on src/GraphQL.Authorization.Tests/AuthorizationValidationRuleTests.cs
> +        // https://github.com/graphql-dotnet/authorization/issues/5
```suggestion
        // https://github.com/graphql-dotnet/authorization/issues/5
        [Fact]
```

2021-12-07 09:39 UTC, sungam3r approved these changes

2021-12-07 09:46 UTC, sungam3r commented
@SlavaUtesinov Thanks to fix the oldest bug!

2021-12-07 12:36 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +                    if (context.TypeInfo.GetAncestor(i++) == actualOperation)
```suggestion
                    // TODO: rewrite
                    if (context.TypeInfo.GetAncestor(i++) == actualOperation)
```

2021-12-07 16:18 UTC, Shane32 requested changes
Can we please add a failing test with a query of this nature:

```gql
query a {
  ...frag1
}
query b {
  ...frag1
}
fragment frag1 on Query {
  # adminField should fail validation
  adminField
}
```

Ideally it would also allow this query when testing for operation `a`, but this could be a future enhancement:

```gql
query a {
  # a field that passes validation
  userField
}
query b {
  ...frag1
}
fragment frag1 on Query {
  # adminField should fail validation
  adminField
}
```

2021-12-07 16:18 UTC, Shane32 commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +                catch (InvalidOperationException)
I assume this occurs when GetAncestor is passed with a value greater than the ancestor count.  The way this is written, an exception will always occur while validating every field.  This should not be the case.  Exception handling is very slow and interferes with debugging.  This should be rewritten to anticipate that `GetAncestor(i++)` will cause an exception and break the loop prior to the exception being thrown.

2021-12-07 19:33 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +                catch (InvalidOperationException)
Yes, we know about that. It requires more changes in GraphQL.NET. See https://github.com/graphql-dotnet/graphql-dotnet/issues/2735 Fix will be later among other changes in `develop`. I suggest to merge as is.

2021-12-07 19:57 UTC, Shane32 commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +                catch (InvalidOperationException)
It cannot be merged as-is.  Creating a fragment completely bypasses authentication.

2021-12-07 22:38 UTC, Shane32 commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +                catch (InvalidOperationException)
I'd also like to point out that with a small allocation, this PR could VERY EASILY be modified to use the node walker to identify which operation it was within, and in so doing know if it should be checking the field or not.  This small single allocation would far outweigh the many allocations necessary when exceptions are thrown for each field examined in a non-matching operation, and due to how slow exceptions take to create, it would go much much faster.

2021-12-07 22:41 UTC, Shane32 commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +                catch (InvalidOperationException)
The only benefit to changing TypeInfo in GraphQL.NET is to reduce the single allocation to none; there will be no notable performance difference; if anything, it would probably go slower since it has to create a `Stack<T>.Enumerator` and call `MoveNext` a bunch of times rather than a direct memory access to a boolean field.

2021-12-07 22:56 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +                catch (InvalidOperationException)
> It cannot be merged as-is. Creating a fragment completely bypasses authentication.

I mean _as is_ about exception handling around `Stack` object, not about new tests.

2021-12-07 22:59 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +                catch (InvalidOperationException)
I want to rewrite `TypeInfo` in something more comfortable. I don't know yet what exactly.

2021-12-08 00:56 UTC, Shane32 commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +                catch (InvalidOperationException)
Fine, but I wouldn't merge bad code just because we think TypeInfo will be changed.  The fact is with a very little effort this PR could work a lot better given the current state of GraphQL.NET.  And throwing an exception at runtime when no error has occurred is almost always bad code -- especially here where it will do so repeatedly.  There's always time to add another PR if TypeInfo is going to be changed considerably.

2021-12-08 07:39 UTC, SlavaUtesinov commented
I've added desired tests.

2021-12-08 11:11 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +                catch (InvalidOperationException)
https://github.com/graphql-dotnet/graphql-dotnet/pull/2743

2021-12-08 11:53 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +                }
```suggestion
                if (!belongs)
                {
                    if (!(belongs = node is FragmentSpread fragmentSpread && fragmentSpread.Name == fragment.Name))
                        node.Visit(Visit, 0);
                }
```

2021-12-08 11:54 UTC, sungam3r approved these changes

2021-12-08 12:08 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +            var actualOperation = context.Document.Operations.FirstOrDefault(x => x.Name == context.OperationName) ?? context.Document.Operations.FirstOrDefault();
@Shane32 Maybe add `Operation` or `EffectiveOperation` property to the `ValidationContext` ? This is "runtime constant" so no need to be calculated each time here. When I write `Errective` I mean that `OperationName` may be `null` but in fact some operation node still exists (anonymous one).

2021-12-08 12:12 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +                catch (InvalidOperationException)
not needed anymore

2021-12-08 12:13 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +            var actualOperation = context.Document.Operations.FirstOrDefault(x => x.Name == context.OperationName) ?? context.Document.Operations.FirstOrDefault();
not needed anymore

2021-12-08 12:18 UTC, sungam3r commented
Also see #29. I think #29 shoul not be a blocker for this PR.

2021-12-08 20:33 UTC, sungam3r commented
@Shane32  ?

2021-12-08 20:52 UTC, Shane32 commented
I need to re-review

2021-12-10 07:12 UTC, SlavaUtesinov commented
@Shane32 ?

2021-12-10 14:41 UTC, Shane32 approved these changes

2021-12-11 12:17 UTC, merged