Small cleanup
graphql-dotnet/authorization pull request #87
Opened 2020-11-01 18:18 UTC by sungam3r

2020-11-01 18:56 UTC, Shane32 commented
I have not used this repo @sungam3r

2020-11-01 20:26 UTC, sungam3r commented
Don't I bother you with the review anymore?

2020-11-01 20:41 UTC, Shane32 commented
I don’t mind if you tag me of course. But I don’t have the knowledge or time to give a comprehensive review. When I’m able, I’ll skim over the changes and give it the 👍  but I won’t really know how any of the changes affect users. 

(Basically I only focus on changes to the main repo at present)

2020-11-01 21:22 UTC, sungam3r commented on src/GraphQL.Authorization.ApiTests/ApiApprovalTests.PublicApi.GraphQL.Authorization.approved.txt
> +        public ClaimAuthorizationRequirement(string claimType, params string[] allowedValues) { }
New API so 3.1.0

2020-11-01 21:32 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +                    if (context.TypeInfo.GetArgument()?.ResolvedType.GetNamedType() is IComplexGraphType argumentType)
fixes #61

2020-11-01 21:57 UTC, sungam3r commented
@joemcbride PR is ready for review, no breaking changes, one bugfix, many xml docs and some memory optimizations. I have reduced the number of changed files. After this PR is merged I will continue working on #62. There are backward incompatible changes. Maybe I'll make `develop` branch for version 4.0.0.

2020-11-02 18:16 UTC, joemcbride requested changes

2020-11-02 18:16 UTC, joemcbride commented on src/Harness/GraphQL.cs
> -
Since this is such a small example, I think it is better to keep it in a single file.  We have gotten a lot of complaints about "I can't find XYZ".

2020-11-02 18:16 UTC, joemcbride commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +            // TODO: async -> sync transition
The only two ways I can think of to fix this is to add `Task` to the `INodeVisitor` interface or build up the list of checks from the visitor and then loop through them a second time and await the check (kind of like DataLoader).

2020-11-02 18:23 UTC, Shane32 commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +            // TODO: async -> sync transition
If we utilize `ValueTask<T>` in the next major version of GraphQL.Net, we may be able to convert more functions, like `INodeVisitor`, to async without all of the allocations necessary with `Task<T>`.

2020-11-02 18:27 UTC, Shane32 commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +            // TODO: async -> sync transition
`ValueTask` is included with .Net Standard 2.1 and later, and is available as a backwards-compatible library for .Net Standard 2.0.

2020-11-02 19:34 UTC, sungam3r commented on src/Harness/GraphQL.cs
> -
OK. Done.

2020-11-02 19:39 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationValidationRule.cs
> +            // TODO: async -> sync transition
>  or build up the list of checks from the visitor and then loop through them a second time and await the check (kind of like DataLoader).

I thought about it. Can be done in different ways though. I just left a reminder for the future. So far, I had no desire to deal with this place.

2020-11-02 19:40 UTC, sungam3r commented
@joemcbride  OK to merge?

2020-11-02 22:46 UTC, Shane32 commented on src/GraphQL.Authorization/AuthorizationPolicy.cs
> +        }
```suggestion
            => _requirements ?? (_singleRequirement != null ? new[] { _singleRequirement } : Enumerable.Empty<IAuthorizationRequirement>());
```
This reduces memory allocations in all three cases: for multiple members, for a single member, and for zero members.

However, if this is called on a hot path when it contains a single requirement, it's guaranteed to have lower performance than the ORIGINAL code, because using `yield return` or a single-element array both requires an allocation.  Either way this is in addition to the allocation for the enumerator of the underlying array.  Finally, using `yield return` will prevent other optimizations that attempt to retrieve the `Count` of the list from being able to do so.  (e.g. `new List<>(oldList)`).  So if other code relies on this property, it's nearly guaranteed that this "optimization" will result in poorer performance than the original code here.

2020-11-02 22:46 UTC, Shane32 commented on src/GraphQL.Authorization/AuthorizationPolicy.cs
> +                    _singleRequirement = temp[0];
If you're really trying to reduce allocations, then this is quite poor code -- it copies the array and then immediately discards it if it's only one member.  It should get the enumerator, attempt to pull and validate a single item, if successful then attempt to pull and validate a second item, and if successful, check if `requirements` implements `ICollection`, pull the Count, allocate a list of the proper size (if known), add the first two members, then continue adding and validating the remaining members.  If single or none, it would set it without ever allocating a List or its underlying array.

If you're not going to follow through, I wouldn't make any of these "optimizations" in this class.  It just isn't worth it.

2020-11-02 22:47 UTC, Shane32 reviewed
I think the "optimizations" within AuthorizationPolicy should be reverted, as the performance should be better with the old code.

2020-11-03 13:04 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationPolicy.cs
> +        }
Yes, I know. I'll revert this code. I wrote it a long time ago and now I am not so happy with it.

2020-11-03 13:14 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationPolicy.cs
> +        }
Reverted.

2020-11-03 13:15 UTC, sungam3r commented on src/GraphQL.Authorization/AuthorizationPolicy.cs
> +                    _singleRequirement = temp[0];
Reverterd. I argee - it just isn't worth it.

2020-11-03 21:22 UTC, joemcbride approved these changes

2020-11-03 22:09 UTC, merged